### ISSUE TITLE
jakub-onderka/php-console-highlighter abandoned

### ISSUE THREAD

**Issue by repat** [povils/phpmnd#106]
> Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead

**Comment by aaajeetee** [comment]
In https://github.com/povils/phpmnd/pull/105 I use the new package (`php-parallel-lint/php-console-highlighter`).

**Comment by repat** [comment]
@povils can you update to this repo instead? :)

**Comment by aaajeetee** [comment]
I think this issue can be closed because #105 is merged. Correct me if I'm wrong.

**Comment by repat** [comment]
@povils @aaajeetee only if a new version is released. the current one is still 2.2.0: https://packagist.org/packages/povils/phpmnd#v2.2.0

**Comment by aaajeetee** [comment]
@repat okay sure, fair point.

**Comment by oallain** [comment]
Hi @povils ,

Can you make a new tag to add these changes?
It will also help me a lot.

Thank you

**Comment by povils** [comment]
Hey everyone!
I release v2.3.0 :)

**Comment by vpassapera** [comment]
This is not fixed.

**Comment by vpassapera** [comment]
Please release a 2.5 version officially to address this ticket.

Thank you.

**Comment by exussum12** [comment]
I have added a the alias 2.5-dev for now, I think we should wait for @sidz changes to be backported for the official 2.5 release (unless there is a breaking change ? - What's your thoughts @sidz )

**Comment by sidz** [comment]
yeah lets wait a bit. I've already started to move my changes to this repo.

**Comment by sidz** [comment]
finalyy released https://github.com/povils/phpmnd/releases/tag/v2.5.0

FYI @vpassapera
