### ISSUE TITLE
Update Composer To Support Latest Version of php-timer

### ISSUE THREAD

**Issue by RichVRed** [povils/phpmnd#108]
The latest version of php-timer is 5.0.1 and thus need to update:

https://github.com/povils/phpmnd/blob/00b6170f7b7af0b7396d1117458ce6fb87a0eb8d/composer.json#L21

to:
`"phpunit/php-timer": "^2.0||^3.0||^4.0||^5.0" `

https://github.com/sebastianbergmann/php-timer
Releases: https://github.com/sebastianbergmann/php-timer/tags

**Comment by exussum12** [comment]
Im not sure phpmnd even needs to depend on that package.

**Comment by web-dc** [comment]
When there'll be a new release? Right now it cannot be used with newest phpunit versions anymore.

**Comment by szepeviktor** [comment]
Done https://github.com/povils/phpmnd/blob/master/composer.json#L21
