### ISSUE TITLE
Syntax error when using class called `Match` in the code

### ISSUE THREAD

**Issue by ksowa** [povils/phpmnd#118]
Example file:

```
<?php
declare(strict_types=1);

namespace Test;

class Match
{
    public function compareTo(Match $other)
    {
        // do something
    }
}
```

Call:
```
phpmnd test.php
```

Expected result (more or less):
```
phpmnd 2.3.0 by Povilas Susinskas
--------------------------------------------------------------------------------
Total of Magic Numbers: 0
Time: 54 ms, Memory: 12.00 MB
```

Insted it returns:
```
phpmnd 2.3.0 by Povilas Susinskas
Syntax error, unexpected T_MATCH, expecting T_STRING on line 6
--------------------------------------------------------------------------------
Total of Magic Numbers: 0
Time: 65 ms, Memory: 12.00 MB
```

More info:
```
# php -v
PHP 7.4.11 (cli) (built: Oct 13 2020 10:09:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with blackfire v1.42.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire
```

**Comment by kylekatarnls** [comment]
I will check that, but I guess it's because of the `match` reserved statement introduced in PHP 8 https://wiki.php.net/rfc/match_expression_v2

The native PHP function `token_get_all()` we use may already detect it.

**Comment by kylekatarnls** [comment]
Actually, `T_MATCH` can only be returned in PHP 8, so I'm pretty sure you're actually running phpmd with PHP 8 and not PHP 7.4
https://3v4l.org/HWvAP

In this case, this behavior is correct as `class Match {}` is invalid in PHP 8.

**Comment by ksowa** [comment]
@kylekatarnls thank you for your input. 

It's not possible I use PHP 8 for that. I'm inside Docker container based on `php:7.4-fpm` image.

Would you like me to prepare an example you could run on your machine?

**Comment by ksowa** [comment]
@kylekatarnls, I've prepared an example Docker environment with php:7.4-cli, where the bug can be easily reproduced.

Please take a look into https://github.com/ksowa/phpmnd-bug-reproduction

**Comment by dlakomski** [comment]
The problem is probably with `nikic/php-parser` library, which is using forward-emulation by default: https://github.com/nikic/PHP-Parser/issues/715#issuecomment-697194296

**Comment by ksowa** [comment]
Thanks @dlakomski!

I've created a PR which resolves this problem: https://github.com/povils/phpmnd/pull/119
