### ISSUE TITLE
Extensions...many words, much typing

### ISSUE THREAD

**Issue by padraic** [povils/phpmnd#12]
Just a quick question on whether having an "all" extensions option would be appropriate, or is there a deliberate choice to make that slightly hard (e.g. users not understanding it's not necessarily a good idea as Step 1).

**Comment by povils** [comment]
@padraic thanks for suggestion :)
After some thinking about it I believe 'all' extension is a valid use case. Thus I'll implement it soon :)

**Comment by ravage84** [comment]
What about files without extensions? How would they be treated. (Not that having PHP files with no extension would be a good idea anyway...)

**Comment by povils** [comment]
This issue has nothing to do with file extensions.

**Comment by povils** [comment]
#47
