### ISSUE TITLE
PHP 8 

### ISSUE THREAD

**Issue by Aseksas** [povils/phpmnd#122]
Root composer.json requires php ^8.0 but your php version (7.4.14) does not satisfy that requirement.

**Comment by sidz** [comment]
there are 2 open PRs already:
- https://github.com/povils/phpmnd/pull/121
- https://github.com/povils/phpmnd/pull/117

**Comment by sidz** [comment]
For those who are looking compatibility with PHP 8:

I forked this repo as looks like maintainer busy or stopped maintaining this project and released a new version with PHP 8 compatibility.

https://github.com/sidz/phpmnd

p.s. I'm okay to backport all future changes back to this repo or archive my folk in favor of original authors repo in case maintainer back.

**Comment by maks-rafalko** [comment]
Thank you @sidz 

@povils - please, please consider adding new collaborator(s) to this repo. It will eliminate issues like this. There are many developers who can help, but no one wants to support their forks.

**Comment by 50bhan** [comment]
@maks-rafalko Exactly! I think many developers can help here and if @povils can't maintain this repo anymore, he can get some help from others to solve this kind of issue. No one likes to fork a repo and start to maintain it all by himself. So, please add some new collaborators.

**Comment by povils** [comment]
Hey! Sorry for the late involvement, recent times weren't offering a lot of free time. I will get into merging these PRs. 
On collaboration side, is anyone interested to help me to keep an eye on it?

**Comment by maks-rafalko** [comment]
> On collaboration side, is anyone interested to help me to keep an eye on it?

@povils, I'm ready to be a collaborator. We use `phpmd` on daily basis on our CI, so at least for the near future, I will be interested in keeping it up to date. My colleague @sidz had to support his own fork for us, since we upgraded to PHP8. 

We would like to avoid such cases and better to keep this main repo up to date.

**Comment by sidz** [comment]
I'm okay to help as well.

**Comment by exussum12** [comment]
@povils  I am also happy to help out.

**Comment by kubawerlos** [comment]
@exussum12 what do you want to help with? Support to PHP 8 is already added: https://github.com/povils/phpmnd/blob/v2.4.0/composer.json#L16

**Comment by exussum12** [comment]
@kubawerlos taking on the collaboration side of phpmnd

**Comment by sasezaki** [comment]
@povils 
Please consider above candidates to collaborators.

**Comment by povils** [comment]
Hey! I added 3 more collaborators! :) @sidz @exussum12 @kubawerlos  thank you so much  for helping on this

**Comment by sidz** [comment]
@povils thank you for your trust. I'll try to backport all changes which I made in my fork into this repository as soon as possible (next week I think)

**Comment by exussum12** [comment]
This issue seems to be resolved now then. So closing

p.s. Thanks @povils for the trust :)
