### ISSUE TITLE
New release needed !

### ISSUE THREAD

**Issue by christophedebatz** [povils/phpmnd#123]
Hi everybody,

Thanks for this great work.

I wondering if it would be possible to release a new minor version that embeds this commit https://github.com/povils/phpmnd/commit/310eb6c987fc37a1887bdf5399421901a9f81ee7. Actually we are forced to pull the dev-master on our Satis and it could be great to create a release instead ;-) 

Thanks per advance,

**Comment by maks-rafalko** [comment]
while we all are waiting for @povils:

from https://github.com/povils/phpmnd/issues/120#issuecomment-783935547

> @maciejzgadzaj see [#122 (comment)](https://github.com/povils/phpmnd/issues/122#issuecomment-782088967)
> 
> @sidz had to fork this repo in order to merge more needed PRs, including support for PHP 8. And the new composer packages was released.
> 
> You can use `composer require phpmnd/phpmnd`
> 
> Hopefully, @povils will add more collaborators to this repo and all new PRs will be merged back here

**Comment by povils** [comment]
Released https://github.com/povils/phpmnd/releases/tag/v2.4.0 :)
