### ISSUE TITLE
Cache failure in CI

### ISSUE THREAD

**Issue by szepeviktor** [povils/phpmnd#124]
`path: ~/.composer/cache/files` tilde is not expanded by GHA.

Please see https://github.com/ergebnis/php-library-template/blob/9f19720edb26c1ce11ea3a571cc751eb36556e7d/.github/workflows/integrate.yaml#L49-L55 - the mother of all GHA configs.

**Comment by exussum12** [comment]
This has been resolved now

**Comment by szepeviktor** [comment]
Thank you. https://github.com/povils/phpmnd/commit/29109fdbac082df1762457f85835296d74fcfb06

Please reconsider using the above linked solution.

**Comment by exussum12** [comment]
Probably more for @povils than me. It's a bigger change than just caching the wrong path
