### ISSUE TITLE
Possible constants hinting

### ISSUE THREAD

**Issue by Asera** [povils/phpmnd#13]
I thought about implementing of showing possible constants for magic numbers and strings. I will not mention strings below, as I think the principles for numbers and strings are similar. Below I will describe possible interface implementation and some thougts about probability of constants hinting.
Below is the example of an interface implementation for console output:

```
--------------------------------------------------------------------------------

src/SomeTestFile.php:34. Magic number: 1121
Possible constants:
	SomeTestFile::SOME_NUMBER
  > 34|         if (($x == 1121) || ($x == 2351)) {

src/SomeTestFile.php:34. Magic number: 2351
Possible constants:
	SomeTestFile::SOME_OTHER_NUMBER
  > 34|         if (($x == 1121) || ($x == 2351)) {

--------------------------------------------------------------------------------
```

Constant hinting:
I was thinking about this idea for some time, and found out that all the use-cases of magic numbers can be divided into two big groups:
- There are constants for some of the magic numbers, but we don't use them for some reason(e.g. we don't know about their existence or we refactor legacy code after constants appearance)
- There are no constants in our project at all, so we use magic numbers
First group can be covered easily by indexing all project constants(and, maybe, PHP constants) and comparing each new found constant with indexed list. All matching constants will be shown as possible constants.
I didn't find good implementation ideas for the second group as we cannot predict what meaning a number has and whether two equal numbers have equal meaning or not.

This description does not covers some interesting topics like constant order in hints, number of constants shown in hints etc. But I think they can be specified later.

**Comment by povils** [comment]
@Asera thank for suggestion :)
To be honest I was thinking about this feature from beginning. With many things I agree. About 1 group:
And what do you think about constants that are not in you project but they are as your dependency(in your vendor).
About second one yes it is practically impossible. But I think there are numbers where we could probable hint. For example: 404 -> HTTP_NOT_FOUND, 200 -> HTTP_OK and all other http response codes. Or 3306 -> MYSQL_PORT and so on.

**Comment by Asera** [comment]
First group
I think all the constants that can be extracted from user source files including vendor folder must be indexed. 
Also PHP itself has some constants and I saw some cases when magic numbers were PHP predefined constants.

Second group
We could make hints for common and widespread numbers. I was thinking about custom user dictionary for magic numbers, but i found it useless as all the constants are already included in project files. And if user needs dictionary he can define constants in his project, this will be the best solution.

**Comment by povils** [comment]
I dont think so that vendor should be included. Firstly it would increase analysis time dramatically. Secondly it is very hard to determine is the constant was found in direct dependency.

**Comment by povils** [comment]
#49
