### ISSUE TITLE
Add ncurses dependency or test tput availability

### ISSUE THREAD

**Issue by a-menshchikov** [povils/phpmnd#153]
When run phpmnd in an alpine container without ncurses I get an error `sh: tput: not found`.

**Comment by exussum12** [comment]
Does phpmnd stop working or just emit that as a warning ? Have you got a container you were working with ?

**Comment by a-menshchikov** [comment]
Just print a warning in terminal.
Now I can't take you a container at the moment, but you can test this issue on any `php:*-cli-alpine` image (or any other that has no ncurses installed).

**Comment by exussum12** [comment]
I will at silencing that warning, as there is code to handle it not working. Thanks!

**Comment by sidz** [comment]
Fixed in 3.0

**Comment by sidz** [comment]
Fixed in https://github.com/povils/phpmnd/releases/tag/v3.2.0
