### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kukukk** [povils/phpmnd#157]
Could you, please, release a new version with symfony 6 support?

**Comment by sidz** [comment]
we would like to merge https://github.com/povils/phpmnd/pull/151 first. So we are a bit blocked.

**Comment by oallain** [comment]
PR #161 now has 2 checks, I think a new tag will appear asap :)

**Comment by sidz** [comment]
Will do in the middle of the next week.

сб, 2 июл. 2022 г., 21:21 oallain ***@***.***>:

**Comment by sidz** [comment]
Done
