### ISSUE TITLE
tput binary not found in alpine based images

### ISSUE THREAD

**Issue by siemendev** [povils/phpmnd#158]
Hi folks,
when using a alpine based docker image, there is no executable "tput" available, which results in the following output:
```
phpmnd version 2.5.0 by Povilas Susinskas


sh: tput: not found

--------------------------------------------------------------------------------

Total of Magic Numbers: 0
Time: 00:00.131, Memory: 17.15 MB
```

Here's the use: app/vendor/povils/phpmnd/src/Printer/Console.php:28
Even though there's a fallback, you may be able to work around that issue using Symfony\Component\Console\Application::getTerminalWidth() from symfony/console:
https://symfony.com/blog/new-in-symfony-3-2-console-improvements-part-2

**Comment by sidz** [comment]
> Even though there's a fallback, you may be able to work around that issue using Symfony\Component\Console\Application::getTerminalWidth()

Unfortunately we can't use as this method as it has been removed since 4.0 (proof https://github.com/symfony/console/blob/5.4/CHANGELOG.md#400)

Btw `tput` usage has been removed in the current master branch.

**Comment by sidz** [comment]
duplicates https://github.com/povils/phpmnd/issues/153
