### ISSUE TITLE
Provide File Extension CLI parameter

### ISSUE THREAD

**Issue by ravage84** [povils/phpmnd#16]
It would be nice to be able to define which files get checked by providing a comma separated list of file extensions.

That could look like:

````
$ phpmnd cakephp-app --file-extensions=php,php5,ctp,bla.foo
``````

The above would check files with the following file extension:

- php
- php5
- ctp
- bla.foo

This is relevant for every PHP project that has more than just the typical ``.php`` files.
For example, CakePHP has template files with the ``.ctp`` extension.

**Comment by ravage84** [comment]
PHPMD, for example has a ``--suffixes`` CLI parameter:

> --suffixes - Comma-separated string of valid source code filename extensions, e.g. php,phtml.

https://phpmd.org/documentation/index.html

**Comment by povils** [comment]
#42
