### ISSUE TITLE
Version 3.0 still renders version 2.5

### ISSUE THREAD

**Issue by leonardfischer** [povils/phpmnd#162]
Hello,

when running version 3.0 of the magic number detection it still runs with this output

```
phpmnd version 2.5.0 by Povilas Susinskas
```

https://github.com/povils/phpmnd/blob/24d250936880ef803ed7a4c4559331e1641ba4e1/src/Console/Application.php#L17

**Comment by sidz** [comment]
Thanks for report this issue. But I can't do anything due to lack of reviewers.

TBH I decided to write a couple phpstan rules instead of using phpmnd.

p.s. I'm happy to create PR in case anybody review them :)

**Comment by maks-rafalko** [comment]
> TBH I decided to write a couple phpstan rules instead of using phpmnd.

Please, make sure to share them if they will be finished one day ;)

**Comment by maks-rafalko** [comment]
> p.s. I'm happy to create PR in case anybody review them :)

@exussum12 could you please help here?

**Comment by exussum12** [comment]
Added a PR if you could approve @sidz  https://github.com/povils/phpmnd/pull/163

**Comment by sidz** [comment]
it would be nice to update CHANGELOG.md. Unfortunately I don't have access to do it in master so it is possible only within new PR

**Comment by exussum12** [comment]
Added the changelog to the PR too

**Comment by leonardfischer** [comment]
Thank you for looking into this :) It was quite confusing when reading logs from our CI server

**Comment by sidz** [comment]
released https://github.com/povils/phpmnd/releases/tag/v3.0.1 

thanks @leonardfischer
