### ISSUE TITLE
phpunit/php-timer v6 support?

### ISSUE THREAD

**Issue by julianphp** [povils/phpmnd#165]
Hi, I have a project with PHP 8.2 and Laravel 10, I had phpunit 9 and no problem, I am trying to upgrade to version 10 and after verifying everything, phpmnd gives problems with phpunit/php-timer and version 6 required for phpunit 10.

  Problem 1
    - Root composer.json requires povils/phpmnd ^3.0 -> satisfiable by povils/phpmnd[v3.0.0, v3.0.1].
    - povils/phpmnd[v3.0.0, ..., v3.0.1] require phpunit/php-timer ^2.0||^3.0||^4.0||^5.0 -> found phpunit/php-timer[2.0.0, ..., 2.1.3, 3.0.0, ..., 3.1.4, 4.0.0, 5.0.0, 5.0.1, 5.0.2, 5.0.3] but it conflicts with your root composer.json require (^6.0).

**Comment by sidz** [comment]
3.1.0 has been released: https://github.com/povils/phpmnd/releases/tag/v3.1.0
