### ISSUE TITLE
[Question] Which output formats are available?

### ISSUE THREAD

**Issue by mimmi20** [povils/phpmnd#168]
Is there a list of output formats which are available in this tool? If there were supported formats like junit or checkstyle it would be easier to integrate with the tools we currently use.

**Comment by sidz** [comment]
Hi @mimmi20 
XML (was added https://github.com/povils/phpmnd/pull/70). Try to add `--xml-output` option.

--xml-output

**Comment by mimmi20** [comment]
Thanks for your answer
