### ISSUE TITLE
Latest tag has previous version code

### ISSUE THREAD

**Issue by achertovsky** [povils/phpmnd#178]
If download https://github.com/povils/phpmnd/archive/refs/tags/v3.4.0.zip and check file src/Console/Application.php you could find there 3.3.0 in constant.

So assumption that something went wrong on tagging/release and previous version was released under it.

**Comment by sidz** [comment]
Yeah. That's a known issue @achertovsky. I raised a PR https://github.com/povils/phpmnd/pull/177 but didn't get any approvals so far

**Comment by exussum12** [comment]
Approved sorry for delay!

**Comment by sidz** [comment]
New version released
