### ISSUE TITLE
CLI Usage GIF

### ISSUE THREAD

**Issue by ravage84** [povils/phpmnd#18]
It would be nice to have a GIF of a usage example.

Like [those](https://www.google.com/search?q=cli+gif+php&tbm=isch).

Such a GIF could be added to the info website from #17.

**Comment by povils** [comment]
Would be great to have a label "nice to have" :D

**Comment by ravage84** [comment]
You can create labels yourself.
https://github.com/povils/phpmnd/labels

**Comment by padraic** [comment]
@povils I suggest not to create 100 labels. I know the temptation! Resist! 😀

**Comment by povils** [comment]
@ravage84 thanks! :)
@padraic i'll try to not :D
