### ISSUE TITLE
Integrate with Stickler CI

### ISSUE THREAD

**Issue by ravage84** [povils/phpmnd#25]
Integrate with [Stickler CI](https://stickler-ci.com/) to check and enforce the coding style of your choice (PSR-2, i believe).

**Comment by raphaelstolt** [comment]
Would opt for the utilisation of PHP CodeSniffer or PHP Coding Standards Fixer to achieve this during Travis CI builds.

**Comment by ravage84** [comment]
The visibility is just not the same.

**Comment by ravage84** [comment]
Alternatives are:
- https://styleci.io/
- https://nitpick-ci.com/#pricing

Still recommend Stickler CI, though.

**Comment by padraic** [comment]
I haven't used Stickler, but StyleCI works fairly well. Even allows you to automatically generate a PR back to the source branch for fixes. That said, most style fixes should be relatively simple so any option would be fine, so long as there's something keeping an eye on it.

**Comment by povils** [comment]
I really dont want to integrate so many xCI. Lets keep them as few as possible.

**Comment by ravage84** [comment]
Sure, your choice.
