### ISSUE TITLE
Add a change log

### ISSUE THREAD

**Issue by ravage84** [povils/phpmnd#27]
Keep a change log, it's best practicse nowadays:

http://keepachangelog.com/en/0.3.0/

For example:
https://github.com/thephpleague/skeleton/blob/master/CHANGELOG.md

**Comment by povils** [comment]
Cant argue with that.

**Comment by ravage84** [comment]
Keeping a change log in a inhouse-project just helped me find the root of an issue. It's really worth-while!

**Comment by povils** [comment]
But dont github releases basically reflect  changelog?( except unreleased features)
I'm looking to at https://github.com/skywinder/github-changelog-generator

**Comment by padraic** [comment]
I think where the problem creeps in is that PR and issue titles don't always explain what changed very well (though they are much better than a commit log dump). They are not always relevant too. For example, PRs on PHPUnit or CI changes aren't relevant to end users. So you could perhaps automatically generate as Step 1, but edit as Step 2?

**Comment by ravage84** [comment]
Neither the commit history of a VCS nor the issue list in an issue tracker replaces a **manually** crafted change log. A change log cannot be automated, otherwise it is just a somewhat fancy version of the commit history. Yes, a change log means work, but a well-made change log has its benefits. Mostly for the users of a library/tool but sometimes even for the developers.

There are several types and levels on how to present changes:

1. Relase Notes, should contain the most important stuff regarding the release, can link to the change log for further details
2. A detailed but curated list of relevant changes (for example, a change log should not contain a change which got reverted within the same release, as if it never happened), can link to commits and/or issues.
3. Issues in a issue tracker, details about planned and implemented changes, connects it to commits, changes  and/or other issues
4. Commits in a VCS, Detail every work done on the code. Not every change will live to see the light as released code

Ever type has its own audience and level of detail.

You can omit the change log, if you do release notes, but this way nobody has a full history of relevant changes without scraping it together from each and every release note.

That's because I keep a change log. Personally I normally do not do release notes, as the change logs of my libraries don't get too bloated.
