### ISSUE TITLE
Support for other Report Output Formats

### ISSUE THREAD

**Issue by ravage84** [povils/phpmnd#31]
[PHP Mess Detector](https://phpmd.org/documentation/index.html) and [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting) support various report output formats.

Supporting certain formats could make the check results of phpmnd non-human processable.

For example, this way, a continuous integration system/service like Scrutinizer could use the results in its application.

**Comment by padraic** [comment]
@povils is probably aware of any MND tooling outside of PHP. They may already have established reporting formats in use that could be adopted (even better if already integrated with a CI somewhere).

**Comment by povils** [comment]
Solved with release 2.0.0
