### ISSUE TITLE
Exit with an evaluable return code

### ISSUE THREAD

**Issue by raphaelstolt** [povils/phpmnd#32]
Currently a command run with n magic numbers found evaluates to 0 via `echo $?`. This should prolly should return a non zero exit code for usage in CI tooling.

**Comment by padraic** [comment]
Actually thinking about it, is detecting magic numbers a signal to fail a build? This is a bit like code coverage or mutation testing - while it might sound tempting to require perfection, in reality it's probably not achievable? The main target in a CI would be to report a decrease or increase in magic numbers as a relative measure of improvement (or not), so you would expect PHPMND to exit with the same code all the time regardless of outcome.

**Comment by raphaelstolt** [comment]
One of the answers PHPMD should provide is if there're magic numbers present in a code base (or more granular in a commit) or not; which should IMHO be reflectable in an exit code. 

For relative measurements like a decrease or increase in magic numbers a seperate command or an option e.g. `--exit-on-detection=false`(1) or `--dry-run`(2) like used by the [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer#using-php-cs-fixer-on-ci)  is imaginable to supress (1) or enforce (2) such an admittedly hard exit.

**Comment by bcremer** [comment]
One can always override the exit code using pipes e.G `vendor/bin/phpmnd || true` if the exit code should not be evaluated by the calling process. So in my opinion phpmnd should return a non zero exit code and individuals can opt out without the need for extra command line options.

**Comment by padraic** [comment]
I'm running against the wind here obviously, so I checked elsewhere and PHPMD (https://phpmd.org/documentation/index.html) does actually exit with a **non-zero** on violations and offer an `--ignore-violations-on-exit` argument to exit with zero. That's the closest equivalent style of detection to PHPMND I can think of, so I retract my argument.

That said, I find it really hard to imagine a scenario where PHPMND would not find a magic number without a lot of exceptions being allowed.

**Comment by povils** [comment]
Thanks guys for discussion. As @padraic  said,  in most cases it is very hard to have codebase without magic numbers and without having a lot of exceptions. I would suggest the same option as @raphaelstolt  suggester ``--exit-on-detection`` or  ``--non-zero-exit-on-violation`` or something. Because in most cases you will find magic numbers, so by default I believe it should be kept as it is now :)

**Comment by povils** [comment]
#51
