### ISSUE TITLE
require_once for vendor/autoload fails on link from directory.

### ISSUE THREAD

**Issue by vpassapera** [povils/phpmnd#45]
https://github.com/povils/phpmnd/commit/df5c2c541e62db63fb7a34afd0aa489f92ddbfd3#diff-743c6cb860ef35ef01f8d2b848a2cb88L18

breaks the command on Centos 7 installation with composer. Previous version worked.

**Comment by padraic** [comment]
The commit left out the autoload path `__DIR__ . '/../../autoload.php'`, where the command is run from `vendor/bin`. I assume @vpassapera has phpmnd installed as a composer dependency?
