### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by IlyaSavich** [povils/phpmnd#57]
Good day, I get an issue for such case. Package doesn't recognize this like a magic number
```
$limit = Carbon::now()->addYears(-123123);
```
Interesting that with the second example works fine
```
$limit = Carbon::now()->addYears(123123);
```
As I understand it's bug or I'm wrong

**Comment by povils** [comment]
Hey,
Thanks for the issue!
Apparently, you are correct, it is a bug:)
Do you want to contribute? And this one? :)

Regards

**Comment by exussum12** [comment]
This looks to be resolved now so the issue can be closed ?
