### ISSUE TITLE
Consider publishing a phar with releases

### ISSUE THREAD

**Issue by jakzal** [povils/phpmnd#73]
I'm maintaining a [docker image with qa tools](https://github.com/jakzal/phpqa) which phpmnd is part of. 

I'm trying to limit number of dependencies installed with "composer global require" to prevent conflicts between tools. Having a phar to download would be really helpful.

**Comment by povils** [comment]
Hey, thanks for the issue. yeah it makes sense

**Comment by jakzal** [comment]
Feature is no longer urgent to me, as I'm planning to introduce the [composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin) in phpqa. It should help solving the conflicts problem.

A phar archive could still be beneficial to others though.

**Comment by patrickjahns** [comment]
Joining the conversation - as I would also appreciate a phar release.

Main reasoning for me is, that our large code bases currently supports php5.6 - php7.2. To be able to solve this we required to set the `platform` to `php 5.6` in `composer.json`. Thus we are not able to require the tool via composer.

However - our CI environment ( as well as some testing environments) are running in php7.1 - so they can parse+analyze the code base easily when running it from a phar



[box]( https://github.com/humbug/box) makes building phar releases very easy 
Played around with **box** and automated phar building - would be happy to help here
https://github.com/patrickjahns/cli-phar-experiments

**Comment by jakzal** [comment]
@patrickjahns in the meantime take a look at the [composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin). You could use it to install any composer tool global in isolation.

**Comment by exussum12** [comment]
Added a PR #77  which allows a phar to be generated
