### ISSUE TITLE
Support ignore annotations

### ISSUE THREAD

**Issue by paslandau** [povils/phpmnd#82]
Hey,

I'm currently running mnd on a larger codebase (~1k classes) and noticed that the tools reports some warnings that I would not consider a problem in the specific context. This clutters the output and prevents a 0 exit code.

It would be great if we could introduce something like 
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file
to mark certain exceptions as "okay".

Currently, I'd have to ignore the whole file via `--exclude-file=.." - which I'd like to avoid.

PS: This frequently happens on the null coalesce operator for setting default values. E.g.

```php
function foo($arg = null){
   $arg = $arg ?? 1000;
}
```

Having that operator "removed" from the "conditions" extension (per config?) would also help a lot ;)

Any thoughts?

**Comment by exussum12** [comment]
We use phpmnd on older / larger code bases with https://github.com/exussum12/coverageChecker
This solves a lot of legacy issues by only checking the changed code. 

The specific example you give there is a magic number no matter how you look at it. Why is it 1000 ? That needs to be explained. There will be a reason for it being 1000. Which can be explained much better in code.

`$arg = $arg ?? self::MICROSECONDS_TO_SECONDS; `

for example

**Comment by paslandau** [comment]
I get your point, I should have used a better example.

Actually, it's a buffer size for an import process. There is no "business logic" for that value. There is imho no inherent value in "extracting" that number in constant, e.g.

```php
function import($bufferSize = null){
   $bufferSize = $bufferSize ?? 1000;
}
```
VS
```php
const BUFFER_SIZE = 1000;

function import($bufferSize = null){
   $bufferSize = $bufferSize ?? self::BUFFER_SIZE;
}
```
Does not make the code any better / more readable.

Regardless it's really not about that specific use case.

There will always be "edgecases" and "opinions" in one way or another and giving people the option to "ignore" something for the time being leads to a much higher acceptance rate. That's way most more mature tools support such an option, e.g:
- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file
- https://phpmd.org/documentation/suppress-warnings.html

**Comment by exussum12** [comment]
Personally I don't have a use case for this

its the difference between 
```

const DEFAULT_BUFFER_SIZE = 1000;

function import($bufferSize = null){
   $bufferSize = $bufferSize ?? self::DEFAULT_BUFFER_SIZE;
}
```
(which actually should be)
its the difference between 
```

const DEFAULT_BUFFER_SIZE = 1000;

function import($bufferSize = self::DEFAULT_BUFFER_SIZE) {
}
```


and

```
function import($bufferSize = null){
   /** @phpmnd:disable */
   $bufferSize = $bufferSize ?? 1000;
   /** @phpmnd:enable */
}
```

It seems more effort to mark it as not a magic number than to just resolve the magic number.

Most other tools do have it though, I would be interested to see the usage of these ignore statements

**Comment by paslandau** [comment]
> It seems more effort to mark it as not a magic number than to just resolve the magic number.

Again - here we just disagree what we see as a magic number. Which is completely fine. 
But I currently do not have the "choice" to to go with my definition - that's the point.

> I would be interested to see the usage of these ignore statements

Example: CodeSniffer with Line length rule (Generic.Files.LineLength)
It's totally reasonable to allow only a certain line length.
But sometimes I'm a couple of characters "above" the limit, e.g.

```php
throw new Exception("Here comes my descriptive explanation why we ended up here ....");
```
Sure, I could do stuff like

```php
$msg = "Here comes my descriptive explanation why we ended up here ...."
throw new Exception($msg);
```
But that doesn't make the code any better / more readable. And I'm strictly against changing something with the only purpose to satisfy some style metric.

Further, "changing" code is always risky. It's much easier to add a
```
// phpcs:disable Generic.Files.LineLength
```
comment.

And yes - in a perfect world we'd always fix/refactor everything immediately and there would be no discussion about what's "correct - but in the real world there are always tradeoffs, opinions, deadlines, priorities etc. :)

**Comment by povils** [comment]
Hey everyone :)
My stand is that it makes more sense to extract a number to constat than put these ugly comments. 
But again I don't see a problem why we couldn't provide a mean to ignore these numbers. 
Are you want to take an ownership of this feature and implement this?
My suggestion for now:
// phpmnd:ignoreLine (ignore line below)

**Comment by exussum12** [comment]
Been thinking of this. You can use intval here it looks much than annotations. Then ignore any intval function calls. We could perhaps do that as standard ? Intval and strval could be added as default ignore parameters ?
