### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by dariuszmaciejewski** [povils/phpmnd#95]
Hello. I see some nice features in the master branch, however the last release is pretty old. Are you going to release a new version soon?

**Comment by alecrabbit** [comment]
Hi! I'll agree it's time for a new release. I couldn't install version 2.1 cause of version collision with php-console-highlighter: I have 0.4, but release 2.1 is demanding 0.3.2

**Comment by MarkVaughn** [comment]
@povils  Any update?

**Comment by povils** [comment]
Hey, thanks for pushing it. I will try this do this Monday))

**Comment by Spudley** [comment]
Did this release happen?

**Comment by MarkVaughn** [comment]
No release since january

**Comment by juliangut** [comment]
New release not happening @povils ?

**Comment by povils** [comment]
Hey, sorry for waiting! 2.2.0 release is here :)
