### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by PauchardThomas** [povils/phpmnd#96]
### Steps to reproduce

1. Downloaded [PHPMND 2.1.0 zip](https://github.com/povils/phpmnd/archive/v2.1.0.zip)
2. Convert zip to phar using https://phar.scer.io/
3. type `php phpmnd.phar  mysrcpath`
4. Nothing happened

**Comment by exussum12** [comment]
That phar converter won't work. There is a createPhar script in the bin directory. 

If you run that you should get a useable phar

**Comment by exussum12** [comment]
Has this been resolved ?

**Comment by exussum12** [comment]
Closing  - please reopen if this is an issue
