### ISSUE TITLE
Support for define() in argument extension

### ISSUE THREAD

**Issue by GaryJones** [povils/phpmnd#99]
```
define( 'FOO__HTTPS_PORT', 80 );
```

That gets identified as a magic number as part of the `argument` extension.

Perhaps an allowance can be made if the magic number is the 2nd argument in a `define()` call?

**Comment by exussum12** [comment]
You can use The `--ignore-funcs=define` parameter not sure if this should be a global default though. I personally use this on an older code base but newer ones avoid using define
